CREATE SCHEMA IF NOT EXISTS shop;


CREATE TABLE IF NOT EXISTS shop.products (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    quantity INTEGER NOT NULL,
    category TEXT NOT NULL
);
